pipeline:
  name: Build aepsdk-places-ios
  identifier: Build_aepsdk_places_ios_1711939679869
  projectIdentifier: Demo_Project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: PS_GitHub_Connector
                    repoName: aepsdk-places-ios
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.Rohan_Dockerhub
                    image: swift:latest
                    shell: Sh
                    command: make build
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: PS_GitHub_Connector
        repoName: aepsdk-places-ios
        build: <+input>
