pipeline:
  name: Build aepsdk-places-ios
  identifier: Build_aepsdk_places_ios_1711939679869
  projectIdentifier: Demo_Project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      git clone prasadsatamharness/aepsdk-places-ios
                      apt-get update
                      apt-get install sudo
                      sudo apt-get install make
                      xcode-select --install
                      make build
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: PS_GitHub_Connector
        repoName: aepsdk-places-ios
        build: <+input>
